{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cricket-feedback.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name | default "default" }}
  labels:
    app: {{ include "cricket-feedback.name" . }}-frontend
    chart: {{ include "cricket-feedback.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cricket-feedback.name" . }}-frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cricket-feedback.name" . }}-frontend
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            {{- toYaml .Values.frontend.env | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
