apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"backend-service","namespace":"cricket-feedback"},"spec":{"ports":[{"port":5001,"protocol":"TCP","targetPort":5001}],"selector":{"app":"backend"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-03T20:15:03Z"
    name: backend-service
    namespace: cricket-feedback
    resourceVersion: "15218"
    uid: 93f3d513-d426-444b-a687-1c3d9ad67e50
  spec:
    clusterIP: 10.96.2.13
    clusterIPs:
    - 10.96.2.13
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
    selector:
      app: backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"frontend-service","namespace":"cricket-feedback"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"frontend"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-03T21:18:58Z"
    name: frontend-service
    namespace: cricket-feedback
    resourceVersion: "32793"
    uid: 15502a7c-9f75-4761-a031-011f37a9c0ba
  spec:
    clusterIP: 10.96.78.180
    clusterIPs:
    - 10.96.78.180
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongodb-service","namespace":"cricket-feedback"},"spec":{"ports":[{"port":27017,"protocol":"TCP","targetPort":27017}],"selector":{"app":"mongodb"},"type":"ClusterIP"}}
    creationTimestamp: "2026-01-03T22:04:27Z"
    name: mongodb-service
    namespace: cricket-feedback
    resourceVersion: "45732"
    uid: fbf504a3-78cb-472b-b062-1450a9c02c85
  spec:
    clusterIP: 10.96.67.159
    clusterIPs:
    - 10.96.67.159
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
